version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    hostname: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "${REDISINSIGHT_PORT}:5540"
    volumes:
      - redis-insight:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
      - postgres-test

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pgdata_test:
  redisdata:
  redis-insight:
